### ISSUE TITLE
Naming bikeshedding for `opcompose` (opposite composition function)

### ISSUE THREAD

**Issue by tkf** [JuliaFunctional/CompositionsBase.jl#3]
I can't really think about a better name but I'd like to rename it if we find a better one.

cc @jw3126

**Comment by tkf** [comment]
Another possible ASCII-based API is to come up with something based on `|>`.  The observation is that, if `|>` has a vararg form

```julia
|>(x, f, g, h) == x |> f |> g |> h == h(g(f(x)))
```

then `opcompose` is `(args...) -> x -> |>(x, args...)`.  So, if we have a "hole" or argument placeholder object, we can use `|>(__placeholder_object__, functions...)` instead of `compose(functions...)`.

This can be done with `<|(functions..., __placeholder_object__)` too.

Implementation:

```julia
struct Hole end
const _ARG_ = Hole()
Base.:|>(::Hole, functions...) = ∘(reverse(functions)...)
<|(args...) = |>(reverse(args)...)
```

Usage:

```julia
julia> |>(_ARG_, sin, cos, tan)
tan ∘ cos ∘ sin

julia> <|(sin, cos, tan, _ARG_)
sin ∘ cos ∘ tan
```

This might be a bit too "fancy" as I want CompositionsBase.jl to be super conservative.  Maybe this can be put in CompositionsX.jl or something.

**Comment by jw3126** [comment]
I like `compose` and `opcompose`. I think `Flux.jl` uses `Chain`, which I also like as a name.

The `Hole()` trick is really clever and your tofu symbol [`◻`](https://github.com/tkf/Tofu.jl/blob/master/src/Tofu.jl#L189) is a good unicode name for it. I agree that this would be a better fit for a fancy CompositionsX.jl package.

Just to remind myself, ideally this package would be part of Base, [it is currently not due to bad font support](https://github.com/JuliaLang/julia/pull/34832).

**Comment by tkf** [comment]
OK, good to have one more "vote" to `opcompose` :) I guess it is likely the current best approach.  I'll experiment the hole thing in CompositionsX.jl.

BTW, just for the record, some more related links:

* https://github.com/JuliaLang/julia/pull/33573 where I failed to convince that defining `const compose = ∘` in `Base` is a good idea.
* https://github.com/JuliaLang/julia/pull/34340 where I'm asking for more pipe-like operators (e.g., `|>>`).
